version: '3.8'

services:
  web:
    build: .
    image: navinvenkat/flaskwebproject1:latest
    container_name: flaskapp
    ports:
      - "8000:8000"
    environment:
      - FLASK_APP=runserver.py
      - FLASK_ENV=production
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8000
    restart: always